# -*- coding: utf-8 -*-
#
# This file is part of React-SearchKit.
# Copyright (C) 2018 CERN.
#
# React-SearchKit is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
sudo: false

language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
