# -*- coding: utf-8 -*-
#
# This file is part of React-SearchKit.
# Copyright (C) 2018 CERN.
#
# React-SearchKit is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
sudo: false

language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage

env:
  global:
      - GH_EMAIL=info@inveniosoftware.org
      - GH_NAME=invenio-developers
      - secure: "OoeSeMqgn8Mpqon/anyrWrm3SjxudQZxw/UJEvL6z38nhmpAdM57Fi3ahYuLmU/RCCYIbY1PuffHt12qq/OZQx0YoRynldZotnP8ZzkZBFryD+Q6g/pktLNwPo90CDxlBbL5DjXkdssJ3WItoKnNUP9pt4GifLa4JQ8Yc5K3MrINocFln7xDPnOvNSybVMAZX4qBvEE4qCVZnZhGXdL4ZscKToUZh2LSHiYdp+fvr2Wr7Z2UMdZTvq5jBYmOkidgurSQd8EXH6NVsEmJ8Vo6mlriqyE5qTdsyXeol9YGNwjrwQTXtnNsA+GFLJmk1T2pAVhM7p4vh71nc3gxOaMlJiOHA3Dx/s/llG+TxBaRqjOffFC/hUG5K8JvB1OqTgy0lMNY6y15eubGTxV7ggWZRin2TxRcYYu2kWlEUn+tFBTSALX4uKRYhVtZUuiqPJElEBOKtcgIAgYzc/e9hLO2498pm/g5OWzy1JxPMBJdzppA3hUv9CWTqK66pdKymWBSkZZ2esvxrbYuIgdCWEJRA9glVr+3Ti5aktkyKzsMdiXBeghq8WOn4XrsAnUpiF+JeQbQeDvb1AT+wJirE0U/0q+AugMKv3SP80PJaTrp/obfSp4mjVz73v9apbeX+Ox2pfkTJDn2sEvhIo0h2FCD5gMxj8Z31RQEHFqEeDSW6qQ="

deploy:
  - provider: script
    script: bash docs/deploy_docs.sh
    keep-history: true
    on:
      branch: master
      repo: inveniosoftware/react-searchkit
  - provider: npm
    email: info@inveniosoftware.org
    api_key:
      secure: ggf80AVCr6Xx2fN3mK7xxtd7oMWJDeWZJRaYXXut3LJpHZy9392CNJQjIiahombphaX7zH29QCozoW/fPXkybkBN9rk+w01Ewrk4+1xPVXMW/f72GR7adzvoA8Wq2O2E8+qqMAYmiD2UrxBhI1yLxPGLJ71tPJz1mDhyEbAmMQHUKN3N1SE/9qL394S2JiJvXYMWaP6FM6++MKXTGVxOspcY60+jI39Tmro66M1B+r+lH+boy7QRDoJy6M85yY3h9GWj/79mhTLIfJoPr8fZOu20S2YTNFsXloM1cW7iwPVdhc3Fo5ptjFFzmeUtKM4llzD1vNyFvciHBBLkCpNV8bdtgG+q3e2PJ2WSrASeAoK5XmlXyssDdy14hnJnRfqRRZOEZvo2nEjqeWGIoYLJUdcBZuhMZhcRW3VIi6pXVckOd3GnYWEBwMTMmjZ1HO0sjdiTTDVNcD/2JGrmqmbsTS4N6sq7yOvv+nhANq/1D2P7OF4rWiYPhrWYQYLsh1KAnSqQXK+1FmsgPOl9kr5Qy3sMog4hOhgkG6QbzjbL29397YGuRaJBTEFKqHmLcnCWDBP+xo91BROnmgyod1CbOG6pyxcm96YICFnHtL7I6ySuaAzmonKr3rq6k7paPwtVhxAXAHDVVOoDGVOv/pXBcEA2xTBrrdX3qGqdL1u0Kys=
    on:
      tags: true
      repo: inveniosoftware/react-searchkit
