/*
 * SPDX-FileCopyrightText: 2018 CERN.
 * SPDX-License-Identifier: MIT
 */

export const SET_QUERY_COMPONENT_INITIAL_STATE = "SET_QUERY_COMPONENT_INITIAL_STATE";
export const SET_QUERY_STRING = "SET_QUERY_STRING";
export const SET_QUERY_SORTING = "SET_QUERY_SORTING";
export const SET_QUERY_SORT_BY = "SET_QUERY_SORT_BY";
export const SET_QUERY_SORT_ORDER = "SET_QUERY_SORT_ORDER";
export const SET_QUERY_STATE = "SET_QUERY_STATE";
export const SET_QUERY_PAGINATION_PAGE = "SET_QUERY_PAGINATION_PAGE";
export const SET_QUERY_PAGINATION_SIZE = "SET_QUERY_PAGINATION_SIZE";
export const SET_QUERY_FILTERS = "SET_QUERY_FILTERS";
export const SET_QUERY_SUGGESTIONS = "SET_QUERY_SUGGESTIONS";
export const SET_SUGGESTION_STRING = "SET_SUGGESTION_STRING";
export const CLEAR_QUERY_SUGGESTIONS = "CLEAR_QUERY_SUGGESTIONS";

export const RESULTS_LOADING = "RESULTS_LOADING";
export const RESULTS_FETCH_SUCCESS = "RESULTS_FETCH_SUCCESS";
export const RESULTS_FETCH_ERROR = "RESULTS_FETCH_ERROR";
export const RESULTS_UPDATE_LAYOUT = "RESULTS_UPDATE_LAYOUT";
export const SET_RESULTS_COMPONENT_INITIAL_STATE =
  "SET_RESULTS_COMPONENT_INITIAL_STATE";
export const RESET_QUERY = "RESET_QUERY";
