'use strict';

exports.__esModule = true;
var ADD_CONFIG = exports.ADD_CONFIG = 'ADD_CONFIG';

var QUERY_RESET_PAGE = exports.QUERY_RESET_PAGE = 'QUERY_RESET_PAGE';
var SET_QUERY_COMPONENT_INITIAL_STATE = exports.SET_QUERY_COMPONENT_INITIAL_STATE = 'SET_QUERY_COMPONENT_INITIAL_STATE';
var SET_QUERY_STRING = exports.SET_QUERY_STRING = 'SET_QUERY_STRING';
var SET_QUERY_SORT_BY = exports.SET_QUERY_SORT_BY = 'SET_QUERY_SORT_BY';
var SET_QUERY_SORT_ORDER = exports.SET_QUERY_SORT_ORDER = 'SET_QUERY_SORT_ORDER';
var SET_QUERY_PAGINATION_PAGE = exports.SET_QUERY_PAGINATION_PAGE = 'SET_QUERY_PAGINATION_PAGE';
var SET_QUERY_PAGINATION_SIZE = exports.SET_QUERY_PAGINATION_SIZE = 'SET_QUERY_PAGINATION_SIZE';
var SET_QUERY_AGGREGATION = exports.SET_QUERY_AGGREGATION = 'SET_QUERY_AGGREGATION';
var SET_STATE_FROM_URL = exports.SET_STATE_FROM_URL = 'SET_STATE_FROM_URL';

var RESULTS_LOADING = exports.RESULTS_LOADING = 'RESULTS_LOADING';
var RESULTS_FETCH_SUCCESS = exports.RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';
var RESULTS_FETCH_ERROR = exports.RESULTS_FETCH_ERROR = 'RESULTS_FETCH_ERROR';
var RESULTS_UPDATE_LAYOUT = exports.RESULTS_UPDATE_LAYOUT = 'RESULTS_UPDATE_LAYOUT';
var SET_RESULTS_COMPONENT_INITIAL_STATE = exports.SET_RESULTS_COMPONENT_INITIAL_STATE = 'SET_RESULTS_COMPONENT_INITIAL_STATE';