export var ADD_CONFIG = 'ADD_CONFIG';

export var QUERY_RESET_PAGE = 'QUERY_RESET_PAGE';
export var SET_QUERY_COMPONENT_INITIAL_STATE = 'SET_QUERY_COMPONENT_INITIAL_STATE';
export var SET_QUERY_STRING = 'SET_QUERY_STRING';
export var SET_QUERY_SORT_BY = 'SET_QUERY_SORT_BY';
export var SET_QUERY_SORT_ORDER = 'SET_QUERY_SORT_ORDER';
export var SET_QUERY_PAGINATION_PAGE = 'SET_QUERY_PAGINATION_PAGE';
export var SET_QUERY_PAGINATION_SIZE = 'SET_QUERY_PAGINATION_SIZE';
export var SET_QUERY_AGGREGATION = 'SET_QUERY_AGGREGATION';
export var SET_STATE_FROM_URL = 'SET_STATE_FROM_URL';

export var RESULTS_LOADING = 'RESULTS_LOADING';
export var RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';
export var RESULTS_FETCH_ERROR = 'RESULTS_FETCH_ERROR';
export var RESULTS_UPDATE_LAYOUT = 'RESULTS_UPDATE_LAYOUT';
export var SET_RESULTS_COMPONENT_INITIAL_STATE = 'SET_RESULTS_COMPONENT_INITIAL_STATE';