export const ADD_CONFIG = 'ADD_CONFIG';

export const SET_QUERY_STRING = 'SET_QUERY_STRING';
export const FETCHING_RESULTS = 'FETCHING_RESULTS';
export const RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';
export const RESULTS_FETCH_ERROR = 'RESULTS_FETCH_ERROR';
