export const ADD_CONFIG = 'ADD_CONFIG';

export const SET_STATE_FROM_URL = 'SET_STATE_FROM_URL';
export const SET_QUERY_STRING = 'SET_QUERY_STRING';
export const SET_QUERY_SORT_BY = 'SET_QUERY_SORT_BY';
export const SET_QUERY_SORT_ORDER = 'SET_QUERY_SORT_ORDER';
export const SET_QUERY_PAGINATION_PAGE = 'SET_QUERY_PAGINATION_PAGE';
export const SET_QUERY_PAGINATION_SIZE = 'SET_QUERY_PAGINATION_SIZE';

export const RESULTS_LOADING = 'RESULTS_LOADING';
export const RESULTS_FETCH_SUCCESS = 'RESULTS_FETCH_SUCCESS';
export const RESULTS_FETCH_ERROR = 'RESULTS_FETCH_ERROR';
export const RESULTS_UPDATE_LAYOUT = 'RESULTS_UPDATE_LAYOUT';
