name: Publish

on:
  push:
    tags:
      - v*

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm install -g npm@latest
          npm ci
          npm run build

      - name: Deploy docs
        run: bash deploy_docs.sh
        env:
          GH_EMAIL: info@inveniosoftware.org
          GH_NAME: inveniobot
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish on NPM
        run: npm publish
