name: Publish

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Update npm
        run: |
          npm install -g npm@latest

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy docs
        run: bash deploy_docs.sh
        env:
          GH_EMAIL: info@inveniosoftware.org
          GH_NAME: inveniobot
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish on npmjs
        run: npm publish
