# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CERN.
# Copyright (C) 2025 KTH Royal Institute of Technology.

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  Publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy docs
        run: bash deploy_docs.sh
        env:
          GH_EMAIL: info@inveniosoftware.org
          GH_NAME: inveniobot
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
